[run]
  deadline = "2m"
  skip-files = [
    "^unsecured/"
  ]

[linters-settings]

  [linters-settings.govet]
    check-shadowing = true

  [linters-settings.gocyclo]
    min-complexity = 40 # 30 by default (but we recommend 10-20)

  [linters-settings.maligned]
    suggest-new = true

  [linters-settings.goconst]
    min-len = 3.0
    min-occurrences = 3.0

  [linters-settings.misspell]
    locale = "US"

  [linters-settings.funlen]
    lines = 100 # default 60
    statements = 80 # default 40

  [linters-settings.gocognit]
    min-complexity = 65 # default 30

  [linters-settings.gofumpt]
    extra-rules = true

[linters]
  enable-all = true
  disable = [
    "testpackage",
    "dupl",
    "lll",
    "gomnd",
    "wsl",
    "goerr113",
    "nestif",
    "nlreturn",
    "exhaustive",
    "wrapcheck",
    "tparallel",
    "exhaustivestruct",
    "paralleltest",
  ]

[issues]
  exclude-use-default = false
  max-per-linter = 0
  max-same-issues = 0
  exclude = ["ST1000: at least one file in a package should have a package comment"]

 [[issues.exclude-rules]]
    path = "(.+)_test.go"
    linters = ["funlen", "goconst", "scopelint"]
